In [65]:
import numpy as np

In [66]:
num1=np.array([1,2,3,4,5],dtype=np.int64)
num2=np.array([1,2,3,4,5],dtype='f')
print(num1.dtype)
print(num1)                                                # making all values as float
print(num2)

int64
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


### taking input from the user

In [67]:
l1=[]
l2=[]
for i in range(1,5):
    inp1=int(input("enter1:  "))
    l1.append(inp1)
for j in range(1,5):
    inp2=int(input("enter2:  "))
    l2.append(inp2)
print(np.array([l1,l2]))

enter1:  1
enter1:  2
enter1:  3
enter1:  4
enter2:  5
enter2:  6
enter2:  7
enter2:  8
[[1 2 3 4]
 [5 6 7 8]]


In [68]:
x=np.array([[1,2,3],[5,6,7],[1,2,3]])
y=np.array([[1,2,3],[5,6,7],[1,2,3]])
print(np.add(x,y))

[[ 2  4  6]
 [10 12 14]
 [ 2  4  6]]


# printing Zero's and One's

#### Zeros are similar to Ones's

In [69]:
ar1_zero=np.zeros(5)
ar1_zero

array([0., 0., 0., 0., 0.])

In [70]:
ar2_zero=np.zeros((3,4))
ar2_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## creating diagonal element

#### 'eye'-method is used

In [71]:
ar_dia=np.eye(5,5)
ar_dia

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# random

##### >creating numpy-arr with random numbers

# rand()

### numpy-arr with random numbers

In [72]:
ran1=np.random.rand(3,4)
ran1

array([[0.42006541, 0.88662161, 0.42437621, 0.87113191],
       [0.91980399, 0.07733105, 0.7744122 , 0.74673479],
       [0.65466716, 0.14110764, 0.02705783, 0.59087244]])

# randn()

###  random value close Zero and +ve or -ve

In [73]:
ran2=np.random.randn(3,4)
ran2

array([[-4.54259849e-01,  1.14246839e+00, -1.41076231e-03,
        -2.53465879e-01],
       [-1.15909732e+00, -4.11656463e-02,  1.51882668e-01,
         2.79986319e-01],
       [ 5.34025358e-01,  9.21134481e-01,  9.80716074e-01,
        -1.58701344e+00]])

# ranf() 

### used to return random values from a uniform distribution in a specified shape

### range from [0.0,1.0) 1.0 is not incuded and 0.0 is included

In [74]:
ran3=np.random.ranf((3,4))
ran3

array([[0.06327404, 0.85814501, 0.01619706, 0.70188358],
       [0.67898557, 0.32101593, 0.86819133, 0.46226659],
       [0.38454612, 0.29457578, 0.9714302 , 0.55680231]])

# randint()

### random value B/W given range

In [75]:
ran1=np.random.randint(1,100,(3,4)) #(3,4)->3x4 matrix 
                                    #1,100->range
ran1

array([[ 3, 71, 91, 13],
       [85, 32, 59, 20],
       [23, 48, 47, 21]])

# shape

In [76]:
arr=np.array([[1,2],[3,4],[5,6]])              # finding matrix type and shape
arr.shape

(3, 2)

# array-shape(Reshape)

In [77]:
res=np.array([[10,20,30],[40,50,60]])
print(res.reshape(3,2))

[[10 20]
 [30 40]
 [50 60]]


# Resize

In [78]:
resi=np.array([1,2,3,4,5,6,7,8,9])
resize_1=np.resize(resi,(2,3))
print(resize_1)

[[1 2 3]
 [4 5 6]]


### converting rows to colums

In [79]:
res1=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(res1)
print()                                                   # " .T "-> is used to transform rows to columns
print(res1.reshape(3,3).T)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[10 40 70]
 [20 50 80]
 [30 60 90]]


### 1D to 2D array

In [80]:
arr1=np.array([1,2,3,4,5,6,7,3])
print(arr1)
print("initial dimentioning: ",arr1.ndim)
print("")
arr2=arr1.reshape(2,4)                                   # 'ndim'-> is used to find dimentioning of given matrix
print(arr2)
print("final dimentioning: ",arr2.ndim)

[1 2 3 4 5 6 7 3]
initial dimentioning:  1

[[1 2 3 4]
 [5 6 7 3]]
final dimentioning:  2


# Mathematical Operaions

### simple operations 

In [81]:
import numpy as np
mat=np.array([1,2,3,4,5])
mat1=np.array([4,6,7,8,9])
var_sum=mat+3                                  # each number is increased by 3 it's work with " + - * / % "
print("increasing the arr by 3:  ",var_sum)

var_sum1=mat+mat1                             # each number in the array is get added with it's corresponding value in the array
print("adding the 2 same length arr:  ",var_sum1)

# it's also written like np.("add","subtract","multiply","divide","mod","power"(mat,mat1),reciprocal(mat || mat1))
# sum=np.add(a,b)

increasing the arr by 3:   [4 5 6 7 8]
adding the 2 same length arr:   [ 5  8 10 12 14]


# Some more Operations

In [82]:
import numpy as np
op1=np.array([1,2,3,67,9,0,65,33])
print("minimum num: ",np.min(op1),"Position: ",np.argmin(op1))
print("maximum num: ",np.max(op1),"Position: ",np.argmax(op1))

# " argmin "-> is to find the min value position
# " argmax "-> is to find the max value position

minimum num:  0 Position:  5
maximum num:  67 Position:  3


In [83]:
op2=np.array([[2,1,3],[9,5,6],[4,8,7]])
print(op2)
print("column min: ",np.min(op2,axis=0))       # 1st column min,2rd column min and 3nd column min
print("row min:    ",np.min(op2,axis=1))       # 1st row min,2rd row min and 3nd row min
print("column max: ",np.max(op2,axis=0))       # 1st column max,2rd column max and 3nd column max
print("row max:    ",np.max(op2,axis=1))       # 1st row max,2rd row max and 3nd row max
# axis =1 for the row
# axis=0 for the column




# in the place of min or max you can use any of 
# "min","max","argmin","argmax","sqrt","sin","cos","cumsum"......... And many more!
# cumsum is [1,4,3]           1st place same
# step-1 ->  [1,1+4,_]        2nd place 1+4 
# step-2 ->  [1,5,5+3]        3rd place 4+3

[[2 1 3]
 [9 5 6]
 [4 8 7]]
column min:  [2 1 3]
row min:     [1 5 4]
column max:  [9 8 7]
row max:     [3 9 8]


# Slicing or accessing in an array

In [84]:
sli=np.array([1,2,3,4,5,6,7])
#             0,1,2,3,4,5,6
#           -7,-6,-5,-4,-3,-2,-1
print("2 to 5:     ",sli[1:5])
print("2 to end:   ",sli[1:])           # x[  start   :  stop  :  step  ]
print("start to 5: ",sli[:5])

2 to 5:      [2 3 4 5]
2 to end:    [2 3 4 5 6 7]
start to 5:  [1 2 3 4 5]


In [85]:
# accessing a value from the matrix
sli1=np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
# printing 2nd row's some elements
print("7to 5: ",sli1[1,2:]) # here '1' stands for 1'st row of the matrix

7to 5:  [7 6 5]


# indentation

In [86]:
ind=np.array([[9,8,7,6],[5,4,3,2]])        # Displaying all the elements in an list type
for i in np.nditer(ind):
    print(i)

9
8
7
6
5
4
3
2


### taking position of all values using row's and column's as (0,1,2,..)

In [87]:
ind1=np.array([[[9,8,7],[5,4,3],[2,6,3]]])
for i,d in np.ndenumerate(ind1):
    print(i,d)
    
# 9 is at 0'th row 0'th column and 3 is at 1'st row 2'nd column

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 1, 0) 5
(0, 1, 1) 4
(0, 1, 2) 3
(0, 2, 0) 2
(0, 2, 1) 6
(0, 2, 2) 3


# Copy vs View

##### actually copy and view both are same but if we change data in view automatically it changes original data

### copy:copy is copy of an array in antother array
### view:view is an otiginal array

In [88]:
a=np.array([1,2,3,4])
co=a.copy()
a[1]=40            # making of 2 as 40
print("original: ",a)
print("copy:     ",co)

original:  [ 1 40  3  4]
copy:      [1 2 3 4]


In [89]:
a1=np.array([1,2,3,4])
vi=a.view()
a1[1]=40            # making of 2 as 40
print("original: ",a1)
print("view:     ",vi)

original:  [ 1 40  3  4]
view:      [ 1 40  3  4]


# searching

#### Searching w.r.t value

In [90]:
sea1=np.array([1,2,3,4,2,5,2,5,6,7])
sea2=np.array([1,3,6,4,7,6,5,4,7,5,4])
#  index       0 1 2 3 4 5 6 7 8 9 10
x_sea1=np.where(sea1==2)
x_sea2=np.where(sea2==4)
print(x_sea1)
print(x_sea2)

(array([1, 4, 6], dtype=int64),)
(array([ 3,  7, 10], dtype=int64),)


#### searchsorted

In [91]:
sor=np.array([1,2,3,4,6,7,8,9,10])
#  index      0 1 2 3 4 5 6 7 8
sor1=np.searchsorted(sor,5)           # at what place in acending order we need to repleace
sor2=np.searchsorted(sor,11) 
print(sor1)
print(sor2)

4
9


# shuffling elements in an array

In [92]:
shu=np.array([1,2,3,4,5,6,7,8])
np.random.shuffle(shu)
print(shu)

[5 1 2 4 8 6 7 3]


#### removing of repeated numbers in an array and transforms into acending order

In [93]:
rep=np.array([1,9,9,9,4,2,4,3,2,3,5,3,7,8,9])
rep1=np.unique(rep)
print(rep1)

[1 2 3 4 5 7 8 9]


# Add or append method

In [94]:
app=np.array([1,2,3,4])
print(app)
app1=np.append(app,7)
print(app1)

[1 2 3 4]
[1 2 3 4 7]


In [95]:
app2=np.array([[1,2,3],[1,2,3]])
app3=np.append(app2,[[11,12,13]],axis=0)
print(app3)

[[ 1  2  3]
 [ 1  2  3]
 [11 12 13]]


# Delete

In [96]:
del1=np.array([1,2,3,4,5])
del2=np.delete(del1,2) # deleting 2'nd index number
print(del2)

[1 2 4 5]


# Matrix

In [97]:
import numpy as np
mat=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
mat1=np.matrix([[1,2,3],[1,2,3],[1,2,3]])
mat2=np.matrix([[1,2,3],[1,2,3],[1,2,3]])
print(mat1+mat2)

[[2 4 6]
 [2 4 6]
 [2 4 6]]


In [99]:
# multiplication of 2 matrix
print(np.matmul(mat1,mat2))

[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


# Transpose of a matrix

### changing rows into columns & colums into rows

In [100]:
trn=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(trn)
print()
print(np.transpose(trn))             #insted of transpose we can use " T "

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# inverse of a matrix

In [101]:
inv=np.matrix([[1,2],[4,5]])
print(np.linalg.inv(inv))

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


# power of a matrix

In [102]:
pov=np.matrix([[1,2],[4,5]])
print(np.linalg.matrix_power(pov,2))  # here 2 is the power

[[ 9 12]
 [24 33]]


# Determinant of a matrix

In [103]:
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print(b)
print()
print("Det: ",np.linalg.det(b))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

Det:  -306.0
